Grails Profiles encapsulate project commands, templates, and plugins.

Grails Webpack Profile is a profile for building Grails applications with node-based frontends via webpack.

To create an application using the `webpack` profile you can use the next command:

[source, bash]
----
grails create-app myapp --profile=org.grails.profiles:webpack:1.1.6
----
(at the time of writing 1.1.6 was the latest version, use whatever version you see fit)

This profile is fairly minimal and is intended as a base for other profiles, such as the https://grails-profiles.github.io/react-webpack/latest/guide/index.html[react-webpack] profile.

It configures webpack to bundle Javacsript source files from src/main/webapp and output them into the `grails-app/assets` directory. Custom tasks are added to build.gradle in order to streamline the bundling process when the Grails application is ran or assembled as a WAR/JAR file.

The profile provides one (optional) feature which installs the https://babeljs.io/)[babel transpiler] to bundle ES6 code. Use the `--features=babel` flag when generating your application to install the feature.

